### ISSUE TITLE
I found issue "get_match_shotmap"

### ISSUE THREAD

**Issue by Gyracat** [federicorabanos/LanusStats#22]
@
<img width="1028" alt="Screenshot 2567-11-04 at 01 13 39" src="https://github.com/user-attachments/assets/e952442a-281b-41cd-9f3e-3e4e00b99560">

**Comment by federicorabanos** [comment]
solucinado con este PR https://github.com/federicorabanos/LanusStats/pull/23, actualiza la libreria
